### PR TITLE
SW-232.

### PR DESCRIPTION
**Pull request by zach-b**

### CODE REVIEW

**Comment by changtengfei** [comment]
@zach-b @Heriam Really thanks for explaining this to us last week. I am planning to play with this code tomorrow. It seems there are some conflicts for this pull request. Could you take a look on that? Thanks!

**Comment by zach-b** [comment]
@changtengfei Merged it with openwsn-berkeley develop branch. Tell us if you encounter any problem while trying it :)

**Comment by zach-b** [comment]
Please merge COAP-31 before merging this one so that ipv4 rovers work too.

**Comment by changtengfei** [comment]
I tried the code and it works well on linux. For windows, not. I will merge this PR and create an issue for window problem later.

**Pull request merged**
