### PR TITLE
SW- Fix a bug introduced by pull request #100

### PR DESCRIPTION
**Pull request by vince-nayal**
Fixing a bug that prevented the creation of motes

### CODE REVIEW

**Comment by twatteyne** [comment]
I'll merge this, but I need to ask you to stick to the workflow (https://openwsn.atlassian.net/wiki/display/OW/Workflow).
Don't hesitate if you have questions about the workflow.
Thanks

**Comment by vince-nayal** [comment]
Thanks,
I tried to create one but i couldn't assign it to myself ?

**Comment by twatteyne** [comment]
I added you to the `developers` group. Can you confirm all is OK?

**Comment by vince-nayal** [comment]
Yes, thank you.

**Comment by twatteyne** [comment]
Excellent!!

**Pull request merged**
